services:
  appointer:
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./attachments:/attachments
      - ./body.txt:/body.txt
